### ISSUE TITLE
Composer.json missing craftcms/cms requirement

### ISSUE THREAD

**Issue by brandonkelly** [importantcoding/ic-omnipay-nmi#1]
Your composer.json must specify a craftcms/cms version, or it won’t show up in the Plugin Store.

**Comment by DarrylHardin** [comment]
Thanks, it has been updated.

**Comment by DarrylHardin** [comment]
Is there something else I need to do? It still isn't showing up in the marketplace.

**Comment by brandonkelly** [comment]
It’s in there now. We’ll look into why it didn’t get picked up automatically.
