### ISSUE TITLE
Abandoned or Updated for Onmi 3

### ISSUE THREAD

**Issue by andrewcgregory** [importantcoding/ic-omnipay-nmi#4]
I noticed it now says:

> ABANDONED (It needs to be upgraded to Omni 3, as it is at present it is a security risk)

However you released 2.0 that says

> Updated for Omni3

Is this plugin actually abandoned and a security risk now or does 2.0 solve this?

**Comment by daniellelecomte** [comment]
hey there @importantcoding - following up here as well. Is this safe to use now? Thanks!

**Comment by andrewcgregory** [comment]
@daniellelecomte I contacted Pixel & Tonic regarding this and they talked to the developer. The response I got back was

> I just had a response and it's ok to use. The sentence was an oversight and will get removed.

So it sounds like it may be OK to use. We had a client using it for 1.5 years without any issues, but because of the limited support and additional features being available we moved them to the authorize.net gateway instead. Hope that helps!
